/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository:
https://github.com/gabeknuth/obsidian-unread-files
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => UnreadFilesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_DATA = {
  readTimestamps: {},
  initialized: false
};
var UnreadFilesPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.data = { ...DEFAULT_DATA };
    this.refreshTimer = null;
    this.saveTimer = null;
  }
  async onload() {
    const stored = await this.loadData();
    this.data = Object.assign({ ...DEFAULT_DATA }, stored);
    if (!this.data.initialized) {
      this.seedAllFiles();
      this.data.initialized = true;
      await this.saveData(this.data);
    }
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file) {
          this.data.readTimestamps[file.path] = Date.now();
          this.debouncedSave();
          this.debouncedRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        const active = this.app.workspace.getActiveFile();
        if (active && active.path === file.path) {
          this.data.readTimestamps[file.path] = Date.now();
          this.debouncedSave();
        }
        this.debouncedRefresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("create", () => this.debouncedRefresh())
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        delete this.data.readTimestamps[file.path];
        this.debouncedSave();
        this.debouncedRefresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (this.data.readTimestamps[oldPath] !== void 0) {
          this.data.readTimestamps[file.path] = this.data.readTimestamps[oldPath];
          delete this.data.readTimestamps[oldPath];
          this.debouncedSave();
        }
        this.debouncedRefresh();
      })
    );
    this.registerEvent(
      this.app.workspace.on(
        "layout-change",
        () => this.debouncedRefresh()
      )
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, abstractFile) => {
        if (abstractFile instanceof import_obsidian.TFile) {
          if (this.isUnread(abstractFile)) {
            menu.addItem((item) => {
              item.setTitle("Mark as read").setIcon("check").onClick(() => {
                this.data.readTimestamps[abstractFile.path] = Date.now();
                this.debouncedSave();
                this.debouncedRefresh();
              });
            });
          } else {
            menu.addItem((item) => {
              item.setTitle("Mark as unread").setIcon("circle").onClick(() => {
                this.data.readTimestamps[abstractFile.path] = 0;
                this.debouncedSave();
                this.debouncedRefresh();
              });
            });
          }
        } else if (abstractFile instanceof import_obsidian.TFolder) {
          if (this.folderHasUnread(abstractFile)) {
            menu.addItem((item) => {
              item.setTitle("Mark folder as read").setIcon("check-circle").onClick(
                () => this.markFolderRead(abstractFile)
              );
            });
          }
        }
      })
    );
    this.addCommand({
      id: "mark-all-read",
      name: "Mark all files as read",
      callback: () => this.markAllRead()
    });
    this.app.workspace.onLayoutReady(() => this.refreshExplorer());
  }
  // ── Core logic ────────────────────────────────────────────────
  seedAllFiles() {
    for (const file of this.app.vault.getFiles()) {
      this.data.readTimestamps[file.path] = file.stat.mtime;
    }
  }
  isUnread(file) {
    if (!(file instanceof import_obsidian.TFile))
      return false;
    const lastRead = this.data.readTimestamps[file.path];
    if (lastRead === void 0)
      return true;
    return file.stat.mtime > lastRead;
  }
  folderHasUnread(folder) {
    if (!folder.children)
      return false;
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && this.isUnread(child))
        return true;
      if (child instanceof import_obsidian.TFolder && this.folderHasUnread(child))
        return true;
    }
    return false;
  }
  markFolderRead(folder) {
    const now = Date.now();
    const walk = (f) => {
      for (const child of f.children) {
        if (child instanceof import_obsidian.TFile) {
          this.data.readTimestamps[child.path] = now;
        } else if (child instanceof import_obsidian.TFolder) {
          walk(child);
        }
      }
    };
    walk(folder);
    this.debouncedSave();
    this.debouncedRefresh();
    new import_obsidian.Notice("Folder marked as read");
  }
  markAllRead() {
    const now = Date.now();
    for (const file of this.app.vault.getFiles()) {
      this.data.readTimestamps[file.path] = now;
    }
    this.debouncedSave();
    this.debouncedRefresh();
    new import_obsidian.Notice("All files marked as read");
  }
  // ── Debounced operations ──────────────────────────────────────
  debouncedRefresh() {
    if (this.refreshTimer)
      clearTimeout(this.refreshTimer);
    this.refreshTimer = setTimeout(() => this.refreshExplorer(), 150);
  }
  debouncedSave() {
    if (this.saveTimer)
      clearTimeout(this.saveTimer);
    this.saveTimer = setTimeout(() => this.saveData(this.data), 2e3);
  }
  // ── Explorer DOM manipulation ─────────────────────────────────
  refreshExplorer() {
    const leaves = this.app.workspace.getLeavesOfType("file-explorer");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (!(view == null ? void 0 : view.fileItems))
        continue;
      const foldersWithUnread = /* @__PURE__ */ new Set();
      const items = view.fileItems;
      for (const path of Object.keys(items)) {
        const item = items[path];
        const selfEl = item.selfEl || item.el;
        if (!selfEl)
          continue;
        const abstractFile = this.app.vault.getAbstractFileByPath(path);
        if (!abstractFile || !(abstractFile instanceof import_obsidian.TFile))
          continue;
        if (this.isUnread(abstractFile)) {
          selfEl.classList.add("is-unread");
          let parent = abstractFile.parent;
          while (parent) {
            if (parent.path !== void 0)
              foldersWithUnread.add(parent.path);
            parent = parent.parent;
          }
        } else {
          selfEl.classList.remove("is-unread");
        }
      }
      for (const path of Object.keys(items)) {
        const item = items[path];
        const selfEl = item.selfEl || item.el;
        if (!selfEl)
          continue;
        const abstractFile = this.app.vault.getAbstractFileByPath(path);
        if (!abstractFile || !(abstractFile instanceof import_obsidian.TFolder))
          continue;
        if (foldersWithUnread.has(path)) {
          selfEl.classList.add("has-unread");
        } else {
          selfEl.classList.remove("has-unread");
        }
      }
    }
  }
  // ── Cleanup ───────────────────────────────────────────────────
  onunload() {
    if (this.refreshTimer)
      clearTimeout(this.refreshTimer);
    if (this.saveTimer) {
      clearTimeout(this.saveTimer);
      this.saveData(this.data);
    }
    document.querySelectorAll(".is-unread").forEach((el) => el.classList.remove("is-unread"));
    document.querySelectorAll(".has-unread").forEach((el) => el.classList.remove("has-unread"));
  }
};
